title: Chaewon's Blog
url: https://chae-jpg.github.io
collections:
  authors: 
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"